version: '3'
services:
  raas:
    image: 'softwaremill/raas:latest'
    ports:
      - '8080:8080'
    depends_on:
      - raas-db
    environment:
      SQL_USERNAME: 'raas'
      SQL_PASSWORD: 'raas'
      SQL_DBNAME: 'raas'
      SQL_HOST: 'raas-db'
      SQL_PORT: '5432'
      API_HOST: '0.0.0.0'
  raas-db:
    image: 'postgres'
    ports:
      - '25432:5432'
    environment:
      POSTGRES_USER: 'raas'
      POSTGRES_PASSWORD: 'raas'
      POSTGRES_DB: 'raas'
